language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_3500de29b3e0_key -iv $encrypted_3500de29b3e0_iv -in turbofats_travis_public.enc -out turbofats_travis_public -d
  - chmod 600 turbofats_travis_public
  - eval $(ssh-agent -s)
  - ssh-add turbofats_travis_public

install:
  - pip install numpy>=1.19.0 Cython>=0.29.0
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coverage

script:
  - coverage run --source late_classifier -m unittest discover

after_success:
  - bash <(curl -s https://codecov.io/bash)
